name: NetworkPlayerSettingsZMenu
version: '${version}'

main: com.stephanofer.networkplayersettingszmenu.NetworkPlayerSettingsZMenuPlugin
api-version: '26.1.2'
load: POSTWORLD
depend: [NetworkPlayerSettings, zMenu]

permissions:
  networkplayersettingszmenu.command.reload:
    description: Reloads safe NetworkPlayerSettingsZMenu runtime resources
    default: op
